window.__LANE_LABELS__ = {
    All: 'All Champions',
    Top: 'Top Lane',
    Jungle: 'Jungle',
    Middle: 'Mid Lane',
    Bottom: 'ADC',
    Support: 'Support'
};

window.__resolveChampionLane = function resolveChampionLane(championId, champion) {
    const laneOverrides = {
        Aatrox: 'Top',
        Ahri: 'Middle',
        Akali: 'Middle',
        Akshan: 'Middle',
        Alistar: 'Support',
        Ambessa: 'Top',
        Amumu: 'Jungle',
        Anivia: 'Middle',
        Annie: 'Middle',
        Aphelios: 'Bottom',
        Ashe: 'Bottom',
        AurelionSol: 'Middle',
        Aurora: 'Middle',
        Azir: 'Middle',
        Bard: 'Support',
        Belveth: 'Jungle',
        Blitzcrank: 'Support',
        Brand: 'Support',
        Braum: 'Support',
        Briar: 'Jungle',
        Caitlyn: 'Bottom',
        Camille: 'Top',
        Cassiopeia: 'Middle',
        Chogath: 'Top',
        Corki: 'Middle',
        Darius: 'Top',
        Diana: 'Jungle',
        Draven: 'Bottom',
        DrMundo: 'Top',
        Ekko: 'Jungle',
        Elise: 'Jungle',
        Evelynn: 'Jungle',
        Ezreal: 'Bottom',
        Fiddlesticks: 'Jungle',
        Fiora: 'Top',
        Fizz: 'Middle',
        Galio: 'Middle',
        Gangplank: 'Top',
        Garen: 'Top',
        Gnar: 'Top',
        Gragas: 'Top',
        Graves: 'Jungle',
        Gwen: 'Top',
        Hecarim: 'Jungle',
        Heimerdinger: 'Middle',
        Hwei: 'Middle',
        Illaoi: 'Top',
        Irelia: 'Top',
        Ivern: 'Jungle',
        Janna: 'Support',
        JarvanIV: 'Jungle',
        Jax: 'Top',
        Jayce: 'Top',
        Jhin: 'Bottom',
        Jinx: 'Bottom',
        Kaisa: 'Bottom',
        Kalista: 'Bottom',
        Karma: 'Support',
        Karthus: 'Jungle',
        Kassadin: 'Middle',
        Katarina: 'Middle',
        Kayle: 'Top',
        Kayn: 'Jungle',
        Kennen: 'Top',
        Khazix: 'Jungle',
        Kindred: 'Jungle',
        Kled: 'Top',
        KogMaw: 'Bottom',
        KSante: 'Top',
        Leblanc: 'Middle',
        LeeSin: 'Jungle',
        Leona: 'Support',
        Lillia: 'Jungle',
        Lissandra: 'Middle',
        Lucian: 'Bottom',
        Lulu: 'Support',
        Lux: 'Support',
        Malphite: 'Top',
        Malzahar: 'Middle',
        Maokai: 'Jungle',
        MasterYi: 'Jungle',
        Mel: 'Middle',
        Milio: 'Support',
        MissFortune: 'Bottom',
        MonkeyKing: 'Jungle',
        Mordekaiser: 'Top',
        Morgana: 'Support',
        Naafiri: 'Middle',
        Nami: 'Support',
        Nasus: 'Top',
        Nautilus: 'Support',
        Neeko: 'Middle',
        Nidalee: 'Jungle',
        Nilah: 'Bottom',
        Nocturne: 'Jungle',
        Nunu: 'Jungle',
        Olaf: 'Jungle',
        Orianna: 'Middle',
        Ornn: 'Top',
        Pantheon: 'Top',
        Poppy: 'Jungle',
        Pyke: 'Support',
        Qiyana: 'Middle',
        Quinn: 'Top',
        Rakan: 'Support',
        Rammus: 'Jungle',
        RekSai: 'Jungle',
        Rell: 'Support',
        Renata: 'Support',
        Renekton: 'Top',
        Rengar: 'Jungle',
        Riven: 'Top',
        Rumble: 'Top',
        Ryze: 'Middle',
        Samira: 'Bottom',
        Sejuani: 'Jungle',
        Senna: 'Support',
        Seraphine: 'Support',
        Sett: 'Top',
        Shaco: 'Jungle',
        Shen: 'Top',
        Shyvana: 'Jungle',
        Singed: 'Top',
        Sion: 'Top',
        Sivir: 'Bottom',
        Skarner: 'Jungle',
        Smolder: 'Bottom',
        Sona: 'Support',
        Soraka: 'Support',
        Swain: 'Middle',
        Sylas: 'Middle',
        Syndra: 'Middle',
        TahmKench: 'Support',
        Taliyah: 'Jungle',
        Talon: 'Middle',
        Taric: 'Support',
        Teemo: 'Top',
        Thresh: 'Support',
        Tristana: 'Bottom',
        Trundle: 'Jungle',
        Tryndamere: 'Top',
        TwistedFate: 'Middle',
        Twitch: 'Bottom',
        Udyr: 'Jungle',
        Urgot: 'Top',
        Varus: 'Bottom',
        Vayne: 'Bottom',
        Veigar: 'Middle',
        Velkoz: 'Support',
        Vex: 'Middle',
        Vi: 'Jungle',
        Viego: 'Jungle',
        Viktor: 'Middle',
        Vladimir: 'Middle',
        Volibear: 'Top',
        Warwick: 'Jungle',
        Xayah: 'Bottom',
        Xerath: 'Support',
        XinZhao: 'Jungle',
        Yasuo: 'Middle',
        Yone: 'Middle',
        Yorick: 'Top',
        Yunara: 'Bottom',
        Yuumi: 'Support',
        Zaahen: 'Top',
        Zac: 'Jungle',
        Zed: 'Middle',
        Zeri: 'Bottom',
        Ziggs: 'Middle',
        Zilean: 'Support',
        Zoe: 'Middle',
        Zyra: 'Support'
    };

    if (laneOverrides[championId]) {
        return laneOverrides[championId];
    }

    const tags = Array.isArray(champion?.tags) ? champion.tags : [];

    if (tags.includes('Marksman')) return 'Bottom';
    if (tags.includes('Support')) return 'Support';
    if (tags.includes('Assassin')) return 'Middle';
    if (tags.includes('Mage')) return 'Middle';
    if (tags.includes('Tank')) return 'Top';
    if (tags.includes('Fighter')) return 'Top';

    return 'Middle';
};
